### ISSUE TITLE
Support for Recipient Feature of Stripe API

### ISSUE THREAD

**Issue by Giovani-Brady** [nberardi/stripe-dotnet#24]
Please review this documentation

https://stripe.com/docs/api#recipients

please note this also affects the Card feature

**Comment by Giovani-Brady** [comment]
addressed in pull requests #28

**Comment by paulirwin** [comment]
The recipients feature is marked as deprecated by Stripe. Is this still worth adding to the library?

**Comment by Giovani-Brady** [comment]
While it is in the process of deprecation for the preferred "Account" feature this addition still has value so long as the API endpoint is available. The new "Account" API endpoints will be added in a follow up pull request.

**Comment by paulirwin** [comment]
PR #31 merged
