### ISSUE TITLE
Update Schedule/Dead Repository

### ISSUE THREAD

**Issue by Giovani-Brady** [nberardi/stripe-dotnet#27]
Is this repository still actively being worked on?

Is there a more active fork to move over to as the main source?

**Comment by Giovani-Brady** [comment]
Is a change of repository ownership something you'd be willing to begin discussing?

**Comment by nberardi** [comment]
@paulirwin has been collaborating on this.  If you are interested, I can add you as a collaborator also.

**Comment by paulirwin** [comment]
How about you get started by submitting a PR? I'm open to adding as a collaborator but a contribution would be the best way to get started.

**Comment by Giovani-Brady** [comment]
@paulirwin Please review Pull Request #28  asap

**Comment by paulirwin** [comment]
I have closed PR #28 with comments there.

I am going to close this discussion as yes, this is the most active fork and the fork that is responsible for the NuGet package. If you have features or fixes you would like to submit, feel free to create issues and submit PRs that reference them.
