### ISSUE TITLE
Stripe no longer supports API requests made with TLS

### ISSUE THREAD

**Issue by NVentimiglia** [nberardi/stripe-dotnet#72]
I got this error making a charge.

{{"error":{"type":"invalid_request_error","message":"Stripe no longer supports API requests made with TLS 1.0. Please initiate HTTPS connections with TLS 1.2 or later. You can learn more about this at https://stripe.com/blog/upgrading-tls."}}}

**Comment by Giovani-Brady** [comment]
@NVentimiglia were you looking to get an update on this package?

@jaymedavis has build out a more thorough implementation that includes this security update here at https://github.com/jaymedavis/stripe.net

**Comment by Giovani-Brady** [comment]
@paulirwin @nberardi @NVentimiglia to provide the stripe recommended changes the framework will need to be upgraded from 4.0 -> 4.5 as Tls12 and Tls11 are not available in 4.0

https://msdn.microsoft.com/en-us/library/system.net.securityprotocoltype(v=vs.100).aspx

**Comment by Giovani-Brady** [comment]
@NVentimiglia this may be too big of change to handle quickly. For an immediate solution refer to @jaymedavis  https://github.com/jaymedavis/stripe.net

**Comment by dananos** [comment]
Hi

   I've found that this code solves the TLS 1.2 issue:

ServicePointManager.SecurityProtocol = (SecurityProtocolType)192 | (SecurityProtocolType)768 | (SecurityProtocolType)3072;

  HTH

**Comment by Giovani-Brady** [comment]
@dananos 

wonderful, care to submit a pull request with some unit/integration tests to verify the fix?
